### ISSUE TITLE
Результат проверки игры "Жизнь"

### ISSUE THREAD

**Issue by dbezhetskov** [MaximBushmakov/Sirius-prog#1]
Хорошо: 
+ управление start / stop
+ возможность задать состояние игры с помощью мыши
+ вменяемый процедурный код

Над чем нужно поработать:
1) doStep сильно перегружена. 

> Функции должны быть маленькими.
> Функция должна выполнять одну задачу

Тут в doStep подмешаны и правила игры и вообще много чего.
Можете сравнить с моим решением - https://github.com/Dima00782/sirius/tree/master/game_of_life
Я не претендую на оптимальность и идеальную красоту кода, но сами посмотрите как легче читать код doStep.

2) Индексы почему-то c 1
`let i = 1; i < this.num_rows + 1; ++i`
мы же программисты, надо привыкать писать с нуля, потом будет проще. 

Могу порекомендовать писать больше программ и потом прочитать книгу:
Clean Code: A Handbook of Agile Software Craftsmanship. Prentice Hall.

**Comment by MaximBushmakov** [comment]
Индексы с 1, потому что field размером num_rows + 2 и num_columns + 2. Клетки с индексами 0 и num_rows + 1/num_columns + 1 проверять не нужно, т.к. они вспомогательные. А правила в класс я не выносил, потому что не собирался изменять, но стоило вынести. Ещё можно было вынести копирование краёв field. Ещё в определении класса 2 раза определялся field[1].
А ещё мне можно будет почитать Code Complete: A Practical Handbook of Software Construction, Steve McConnell.
И как мне писать названия переменных - nextFieldInd, NextFieldInd или next_field_ind?

**Comment by dbezhetskov** [comment]
Стало заметно лучше!
Конечно название *center не сильно отражает что происходит, но это дело вкуса.

**Comment by dbezhetskov** [comment]
По поводу наименований:

> И как мне писать названия переменных - nextFieldInd, NextFieldInd или next_field_ind?

Обычно используют какой-нибудь 1 стиль, я привык к http://google.github.io/styleguide/
Там под все языки написано как называть, где объявлять и т.д.
Следование этому стандарту повысит читаемость кода.

И неплохо бы еще и форматтер какой-нибудь использовать, как например clang-format.
