### ISSUE TITLE
Результаты проверки: нормальные алгорифмы

### ISSUE THREAD

**Issue by bravit** [MaximBushmakov/Sirius-prog#2]
Этот код решает какую-то другую задачу, не ту, которую я ставил. Он слишком сложный, я не могу в нём разобраться за разумное время.

**Comment by MaximBushmakov** [comment]
Посмотрите, пожалуйста NormAlgorithmsLite. Выглядит проще, ближе к задаче.

**Comment by bravit** [comment]
Хорошо! 100 баллов, хотя тестирование в упрощённой версии вы не сделали!
