### ISSUE TITLE
Результат проверки блокиратора

### ISSUE THREAD

**Issue by dbezhetskov** [MaximBushmakov/Sirius-prog#3]
Все работает как надо!
Даже гугл блокируется когда extension включен, что, как по мне, немного неудобно.

Кнопки disable/enable работают.
Кода мало и это хорошо!
Лаба зачтена!

**Comment by MaximBushmakov** [comment]
Блокирует только google.com, поэтому гуглить можно, но правда немного неудобно с гугловскими сайтами.
