### ISSUE TITLE
Результат проверки fingerprint

### ISSUE THREAD

**Issue by dbezhetskov** [MaximBushmakov/Sirius-prog#4]
Совмещаю это с проверкой лабы tracking, потому что лаба фингерпринт уже это делает.

В целом все хорошо, но хардкодить в коде ip не надо было, пришлось прописывать localhost чтобы проверить.
Закомментированный код тоже лучше удалять, чтобы не отвлекал от чтения кода.

**Comment by MaximBushmakov** [comment]
Исправил
